### ISSUE TITLE
Large historical backfills causing Coordinator to crash

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#463] opened 2023-12-20 00:50 UTC
Large historical backfills, e.g. 90M blocks, have been shown to crash the Coordinator machine. The last log message was related to fetching the Delta Lake index files from S3.

This is most likely memory related - Coordinator attempts to aggregate many Index files, eventually running out of memory.

**Comment by darunrs** [comment] 2024-03-11 19:21
Duplicate of https://github.com/near/queryapi/issues/531

**Closed by darunrs** 2024-03-11 19:21 UTC
Labels: bug
